### ISSUE TITLE
Failed to build on github actions with python 3.10

### ISSUE THREAD

**Issue by gaogaotiantian** [andfoy/pywinpty#187] opened 2021-10-16 22:12 UTC
Hi,

I tried to install jupyter through pip in a github action, using Python3.10. However, ``pywinpty`` failed to build. I saw that there's no existing wheels for py3.10 on pypi, is there a plan to support that soon as it's a released stable version now?

Just in case it's useful, the failure on github action is:

```
Building wheels for collected packages: pyrsistent, pywinpty
  Building wheel for pyrsistent (pyproject.toml): started
  Building wheel for pyrsistent (pyproject.toml): finished with status 'done'
  Created wheel for pyrsistent: filename=pyrsistent-0.18.0-cp310-cp310-win_amd64.whl size=62355 sha256=c7b65d474f7a783952e8d793b5ed3ef8376878c9b50bd4ad810b735a9cb5ff44
  Stored in directory: c:\users\runneradmin\appdata\local\pip\cache\wheels\bf\ee\17\b548a960bb9e20daf7987f316c326e8a368603809ace3b2374
  Building wheel for pywinpty (pyproject.toml): started
  Building wheel for pywinpty (pyproject.toml): still running...
  Building wheel for pywinpty (pyproject.toml): finished with status 'error'
  ERROR: Command errored out with exit status 1:
   command: 'C:\hostedtoolcache\windows\Python\3.10.0\x64\python.exe' 'C:\hostedtoolcache\windows\Python\3.10.0\x64\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py' build_wheel 'C:\Users\RUNNER~1\AppData\Local\Temp\tmpfup55p1f'
       cwd: C:\Users\runneradmin\AppData\Local\Temp\pip-install-7_pm70zh\pywinpty_442135e78f79467382751c81f8940a19
  Complete output (138 lines):
  Running `maturin pep517 build-wheel -i C:\hostedtoolcache\windows\Python\3.10.0\x64\python.exe`
     Compiling proc-macro2 v1.0.30
     Compiling unicode-xid v0.2.2
     Compiling syn v1.0.80
     Compiling winapi v0.3.9
     Compiling jobserver v0.1.24
     Compiling windows_reader v0.19.0
     Compiling libc v0.2.104
     Compiling windows_quote v0.19.0
     Compiling proc-macro-hack v0.5.19
     Compiling pyo3-build-config v0.14.5
     Compiling const-sha1 v0.2.0
     Compiling once_cell v1.8.0
     Compiling scratch v1.0.0
     Compiling unicode-width v0.1.9
     Compiling cxxbridge-flags v1.0.56
     Compiling lazy_static v1.4.0
     Compiling cfg-if v1.0.0
     Compiling parking_lot_core v0.8.5
     Compiling either v1.6.1
     Compiling smallvec v1.7.0
     Compiling unindent v0.1.7
     Compiling scopeguard v1.1.0
     Compiling cc v1.0.71
     Compiling windows_gen v0.19.0
     Compiling instant v0.1.11
     Compiling lock_api v0.4.5
     Compiling link-cplusplus v1.0.5
     Compiling cxx v1.0.56
     Compiling quote v1.0.10
     Compiling winapi-util v0.1.5
     Compiling which v4.2.2
     Compiling paste-impl v0.1.18
     Compiling termcolor v1.1.2
     Compiling pyo3 v0.14.5
     Compiling parking_lot v0.11.2
     Compiling paste v0.1.18
     Compiling codespan-reporting v0.11.1
     Compiling cxx-build v1.0.56
     Compiling pyo3-macros-backend v0.14.5
     Compiling windows_macros v0.19.0
     Compiling indoc-impl v0.3.6
     Compiling cxxbridge-macro v1.0.56
     Compiling windows v0.19.0
     Compiling indoc v0.3.6
     Compiling pyo3-macros v0.14.5
     Compiling pywinpty_findlib v0.3.0 (C:\Users\runneradmin\AppData\Local\Temp\pip-install-7_pm70zh\pywinpty_442135e78f79467382751c81f8940a19\local_dependencies\pywinpty_findlib)
     Compiling pywinpty v1.1.4 (C:\Users\runneradmin\AppData\Local\Temp\pip-install-7_pm70zh\pywinpty_442135e78f79467382751c81f8940a19)
  error: failed to run custom build command for `pywinpty v1.1.4 (C:\Users\runneradmin\AppData\Local\Temp\pip-install-7_pm70zh\pywinpty_442135e78f79467382751c81f8940a19)`
  
  Caused by:
    process didn't exit successfully: `C:\Users\runneradmin\AppData\Local\Temp\pip-install-7_pm70zh\pywinpty_442135e78f79467382751c81f8940a19\target\release\build\pywinpty-31e6fd3445e66330\build-script-build` (exit code: 1)
    --- stdout
    cargo:rerun-if-changed=src/lib.rs
    cargo:rerun-if-changed=src/native.rs
    cargo:rerun-if-changed=src/csrc
    cargo:rerun-if-changed=include/
    Windows major version: 10
    Windows build number: 17763
    ConPTY enabled: 1
    winpty version 0.4.3
    commit none
    Using Winpty version:
    cargo:rustc-link-search=native=C:\Program Files\Git\usr\lib
    cargo:rustc-link-search=native=C:\Program Files\Git\usr\bin
    cargo:CXXBRIDGE_PREFIX=pywinpty
    cargo:CXXBRIDGE_LINKS=winpty
    cargo:CXXBRIDGE_DIR0=C:\Users\runneradmin\AppData\Local\Temp\pip-install-7_pm70zh\pywinpty_442135e78f79467382751c81f8940a19\target\release\build\pywinpty-361c0c68071d7855\out\cxxbridge\include
    cargo:CXXBRIDGE_DIR1=C:\Users\runneradmin\AppData\Local\Temp\pip-install-7_pm70zh\pywinpty_442135e78f79467382751c81f8940a19\target\release\build\pywinpty-361c0c68071d7855\out\cxxbridge\crate
    cargo:CXXBRIDGE_DIR2=C:\Users\runneradmin\AppData\Local\Temp\pip-install-7_pm70zh\pywinpty_442135e78f79467382751c81f8940a19\include
    cargo:CXXBRIDGE_DIR3=C:\Users\runneradmin\AppData\Local\Temp\pip-install-7_pm70zh\pywinpty_442135e78f79467382751c81f8940a19
    cargo:CXXBRIDGE_DIR4=C:\Program Files\Git\usr\include
    TARGET = Some("x86_64-pc-windows-msvc")
    OPT_LEVEL = Some("3")
    HOST = Some("x86_64-pc-windows-msvc")
    CXX_x86_64-pc-windows-msvc = None
    CXX_x86_64_pc_windows_msvc = None
    HOST_CXX = None
    CXX = None
    CXXFLAGS_x86_64-pc-windows-msvc = None
    CXXFLAGS_x86_64_pc_windows_msvc = None
    HOST_CXXFLAGS = None
    CXXFLAGS = None
    CRATE_CC_NO_DEFAULTS = None
    CARGO_CFG_TARGET_FEATURE = Some("fxsr,sse,sse2")
    DEBUG = Some("false")
    CXX_x86_64-pc-windows-msvc = None
    CXX_x86_64_pc_windows_msvc = None
    HOST_CXX = None
    CXX = None
    CXXFLAGS_x86_64-pc-windows-msvc = None
    CXXFLAGS_x86_64_pc_windows_msvc = None
    HOST_CXXFLAGS = None
    CXXFLAGS = None
    CRATE_CC_NO_DEFAULTS = None
    CARGO_CFG_TARGET_FEATURE = Some("fxsr,sse,sse2")
    CXX_x86_64-pc-windows-msvc = None
    CXX_x86_64_pc_windows_msvc = None
    HOST_CXX = None
    CXX = None
    CXXFLAGS_x86_64-pc-windows-msvc = None
    CXXFLAGS_x86_64_pc_windows_msvc = None
    HOST_CXXFLAGS = None
    CXXFLAGS = None
    CRATE_CC_NO_DEFAULTS = None
    CARGO_CFG_TARGET_FEATURE = Some("fxsr,sse,sse2")
    running: "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Enterprise\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX64\\x64\\cl.exe" "-nologo" "-MD" "-O2" "-Brepro" "-I" "C:\\Users\\runneradmin\\AppData\\Local\\Temp\\pip-install-7_pm70zh\\pywinpty_442135e78f79467382751c81f8940a19\\target\\release\\build\\pywinpty-361c0c68071d7855\\out\\cxxbridge\\include" "-I" "C:\\Users\\runneradmin\\AppData\\Local\\Temp\\pip-install-7_pm70zh\\pywinpty_442135e78f79467382751c81f8940a19\\target\\release\\build\\pywinpty-361c0c68071d7855\\out\\cxxbridge\\crate" "-I" "C:\\Users\\runneradmin\\AppData\\Local\\Temp\\pip-install-7_pm70zh\\pywinpty_442135e78f79467382751c81f8940a19\\include" "-I" "C:\\Users\\runneradmin\\AppData\\Local\\Temp\\pip-install-7_pm70zh\\pywinpty_442135e78f79467382751c81f8940a19" "-I" "C:\\Program Files\\Git\\usr\\include" "/EHsc" "-D_GLIBCXX_USE_CXX11_ABI=0" "-DENABLE_WINPTY=1" "-DENABLE_CONPTY=1" "-DDEBUG=0" "-FoC:\\Users\\runneradmin\\AppData\\Local\\Temp\\pip-install-7_pm70zh\\pywinpty_442135e78f79467382751c81f8940a19\\target\\release\\build\\pywinpty-361c0c68071d7855\\out\\cxxbridge\\sources\\pywinpty\\src\\native.rs.o" "-c" "C:\\Users\\runneradmin\\AppData\\Local\\Temp\\pip-install-7_pm70zh\\pywinpty_442135e78f79467382751c81f8940a19\\target\\release\\build\\pywinpty-361c0c68071d7855\\out\\cxxbridge\\sources\\pywinpty\\src\\native.rs.cc"
    native.rs.cc
    running: "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Enterprise\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX64\\x64\\cl.exe" "-nologo" "-MD" "-O2" "-Brepro" "-I" "C:\\Users\\runneradmin\\AppData\\Local\\Temp\\pip-install-7_pm70zh\\pywinpty_442135e78f79467382751c81f8940a19\\target\\release\\build\\pywinpty-361c0c68071d7855\\out\\cxxbridge\\include" "-I" "C:\\Users\\runneradmin\\AppData\\Local\\Temp\\pip-install-7_pm70zh\\pywinpty_442135e78f79467382751c81f8940a19\\target\\release\\build\\pywinpty-361c0c68071d7855\\out\\cxxbridge\\crate" "-I" "C:\\Users\\runneradmin\\AppData\\Local\\Temp\\pip-install-7_pm70zh\\pywinpty_442135e78f79467382751c81f8940a19\\include" "-I" "C:\\Users\\runneradmin\\AppData\\Local\\Temp\\pip-install-7_pm70zh\\pywinpty_442135e78f79467382751c81f8940a19" "-I" "C:\\Program Files\\Git\\usr\\include" "/EHsc" "-D_GLIBCXX_USE_CXX11_ABI=0" "-DENABLE_WINPTY=1" "-DENABLE_CONPTY=1" "-DDEBUG=0" "-FoC:\\Users\\runneradmin\\AppData\\Local\\Temp\\pip-install-7_pm70zh\\pywinpty_442135e78f79467382751c81f8940a19\\target\\release\\build\\pywinpty-361c0c68071d7855\\out\\src/csrc/base.o" "-c" "src/csrc/base.cpp"
    base.cpp
    C:\Users\runneradmin\AppData\Local\Temp\pip-install-7_pm70zh\pywinpty_442135e78f79467382751c81f8940a19\include\winpty_common.h(7): fatal error C1083: Cannot open include file: 'winpty.h': No such file or directory
    exit code: 2
    running: "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Enterprise\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX64\\x64\\cl.exe" "-nologo" "-MD" "-O2" "-Brepro" "-I" "C:\\Users\\runneradmin\\AppData\\Local\\Temp\\pip-install-7_pm70zh\\pywinpty_442135e78f79467382751c81f8940a19\\target\\release\\build\\pywinpty-361c0c68071d7855\\out\\cxxbridge\\include" "-I" "C:\\Users\\runneradmin\\AppData\\Local\\Temp\\pip-install-7_pm70zh\\pywinpty_442135e78f79467382751c81f8940a19\\target\\release\\build\\pywinpty-361c0c68071d7855\\out\\cxxbridge\\crate" "-I" "C:\\Users\\runneradmin\\AppData\\Local\\Temp\\pip-install-7_pm70zh\\pywinpty_442135e78f79467382751c81f8940a19\\include" "-I" "C:\\Users\\runneradmin\\AppData\\Local\\Temp\\pip-install-7_pm70zh\\pywinpty_442135e78f79467382751c81f8940a19" "-I" "C:\\Program Files\\Git\\usr\\include" "/EHsc" "-D_GLIBCXX_USE_CXX11_ABI=0" "-DENABLE_WINPTY=1" "-DENABLE_CONPTY=1" "-DDEBUG=0" "-FoC:\\Users\\runneradmin\\AppData\\Local\\Temp\\pip-install-7_pm70zh\\pywinpty_442135e78f79467382751c81f8940a19\\target\\release\\build\\pywinpty-361c0c68071d7855\\out\\src/csrc/pty.o" "-c" "src/csrc/pty.cpp"
    pty.cpp
    exit code: 0
    C:\Users\runneradmin\AppData\Local\Temp\pip-install-7_pm70zh\pywinpty_442135e78f79467382751c81f8940a19\include\winpty_common.h(7): fatal error C1083: Cannot open include file: 'winpty.h': No such file or directory
    exit code: 2
  
    --- stderr
  
    CXX include path:
      C:\Users\runneradmin\AppData\Local\Temp\pip-install-7_pm70zh\pywinpty_442135e78f79467382751c81f8940a19\target\release\build\pywinpty-361c0c68071d7855\out\cxxbridge\include
      C:\Users\runneradmin\AppData\Local\Temp\pip-install-7_pm70zh\pywinpty_442135e78f79467382751c81f8940a19\target\release\build\pywinpty-361c0c68071d7855\out\cxxbridge\crate
      C:\Users\runneradmin\AppData\Local\Temp\pip-install-7_pm70zh\pywinpty_442135e78f79467382751c81f8940a19\include
      C:\Users\runneradmin\AppData\Local\Temp\pip-install-7_pm70zh\pywinpty_442135e78f79467382751c81f8940a19
      C:\Program Files\Git\usr\include
  
  
    error occurred: Command "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Enterprise\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX64\\x64\\cl.exe" "-nologo" "-MD" "-O2" "-Brepro" "-I" "C:\\Users\\runneradmin\\AppData\\Local\\Temp\\pip-install-7_pm70zh\\pywinpty_442135e78f79467382751c81f8940a19\\target\\release\\build\\pywinpty-361c0c68071d7855\\out\\cxxbridge\\include" "-I" "C:\\Users\\runneradmin\\AppData\\Local\\Temp\\pip-install-7_pm70zh\\pywinpty_442135e78f79467382751c81f8940a19\\target\\release\\build\\pywinpty-361c0c68071d7855\\out\\cxxbridge\\crate" "-I" "C:\\Users\\runneradmin\\AppData\\Local\\Temp\\pip-install-7_pm70zh\\pywinpty_442135e78f79467382751c81f8940a19\\include" "-I" "C:\\Users\\runneradmin\\AppData\\Local\\Temp\\pip-install-7_pm70zh\\pywinpty_442135e78f79467382751c81f8940a19" "-I" "C:\\Program Files\\Git\\usr\\include" "/EHsc" "-D_GLIBCXX_USE_CXX11_ABI=0" "-DENABLE_WINPTY=1" "-DENABLE_CONPTY=1" "-DDEBUG=0" "-FoC:\\Users\\runneradmin\\AppData\\Local\\Temp\\pip-install-7_pm70zh\\pywinpty_442135e78f79467382751c81f8940a19\\target\\release\\build\\pywinpty-361c0c68071d7855\\out\\cxxbridge\\sources\\pywinpty\\src\\native.rs.o" "-c" "C:\\Users\\runneradmin\\AppData\\Local\\Temp\\pip-install-7_pm70zh\\pywinpty_442135e78f79467382751c81f8940a19\\target\\release\\build\\pywinpty-361c0c68071d7855\\out\\cxxbridge\\sources\\pywinpty\\src\\native.rs.cc" with args "cl.exe" did not execute successfully (status code exit code: 2).
  
  
  💥 maturin failed
    Caused by: Failed to build a native library through cargo
    Caused by: Cargo build finished with "exit code: 101": `cargo rustc --message-format json --manifest-path Cargo.toml --release --lib --`
  �\x8d� Building a mixed python/rust project
  🔗 Found pyo3 bindings
  �\x90\x8d Found CPython 3.10 at C:\hostedtoolcache\windows\Python\3.10.0\x64\python.exe
  Error: command ['maturin', 'pep517', 'build-wheel', '-i', 'C:\\hostedtoolcache\\windows\\Python\\3.10.0\\x64\\python.exe'] returned non-zero exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for pywinpty
```

**Comment by ccordoba12** [comment] 2021-10-17 04:34
Duplicate of #185

**Closed as completed by ccordoba12** 2021-10-17 04:34 UTC
